"""Indexing the vectors and content in documents

Revision ID: 29ed18deb6c1
Revises: 4489ac9bd33c
Create Date: 2026-07-18 22:20:39.832270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ed18deb6c1'
down_revision: Union[str, Sequence[str], None] = '4489ac9bd33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_content'), 'documents', ['content'], unique=False)
    op.create_index(op.f('ix_documents_embedding'), 'documents', ['embedding'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_embedding'), table_name='documents')
    op.drop_index(op.f('ix_documents_content'), table_name='documents')
    # ### end Alembic commands ###
