"""init

Revision ID: f7e2c455dd91
Revises:
Create Date: 2026-08-18 22:46:58.645317

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision: str = "f7e2c455dd91"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "workspaces",
        sa.Column("workspace_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_table(
        "documents",
        sa.Column("document_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content", app.adapters.orm.ContentType(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("is_preprocessed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.workspace_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        "ix_documents_workspace_preprocessed",
        "documents",
        ["workspace_id", "is_preprocessed"],
        unique=False,
    )
    op.create_table(
        "chunks",
        sa.Column("chunk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("content", app.adapters.orm.ContentType(), nullable=False),
        sa.Column(
            "embedding_vector", app.adapters.orm.EmbeddingVector(dim=384), nullable=True
        ),
        sa.Column("embedding_model_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.document_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("chunk_id"),
        sa.UniqueConstraint("document_id", "content", name="uq_document_content"),
    )
    op.create_index(
        op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index("ix_documents_workspace_preprocessed", table_name="documents")
    op.drop_table("documents")
    op.drop_table("workspaces")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
